### ISSUE TITLE
Nice work but need some automation as user-friendly

### ISSUE THREAD

**Issue by mani2care** [Mac-Nerd/patchomator#1]
hey nice work but enable the parameter option to inject the values like -r - v -c .........
2) why not script to download the files or script auto without asking any pre-request [Installomator] you can add the script to download where you want and validate the version if required 
3) this script is for only scanning the app ? it will not do install the application if older version 
4) is this scanning to all the apps and matching with [Installomator] so after the scan show only update required version 
5) why dont you try with [swiftDialog] script to do this friendly UI scan and after give the available update and install it automatically as predefined with UI.

**Comment by Mac-Nerd** [comment]
Thanks. I've considered a few of these improvements already, but consider my main goal is to be a companion piece to Installomator, not a replacement. 

If you have any suggestions on improvements, I welcome any contributions.
