### ISSUE TITLE
Patchomator does not make the App Support folder

### ISSUE THREAD

**Issue by BigMacAdmin** [Mac-Nerd/patchomator#10]
```
[FATAL ERROR] /Library/Application Support/Patchomator is not writable. Re-run patchomator with sudo to create the config file there, or use a writable path with
	 --config "path to config file"
```

Copied patchomator.sh to `/usr/local/Installomator` and ran it on a fresh VM and this fatal error appears. Script does not properly create its folder dependency.

Error occurs when run via `sudo`

Running this command resolves the issue: `mkdir -p "/Library/Application Support/Patchomator"`

**Comment by Mac-Nerd** [comment]
Good catch. Fixed and closed.
