### ISSUE TITLE
Respect of Options Flag

### ISSUE THREAD

**Issue by davidkrause-campfire** [Mac-Nerd/patchomator#15]
My current command is:

`sudo /usr/local/Installomator/patchomator.sh --yes --options IGNORE_APP_STORE_APPS=no BLOCKING_PROCESS_ACTION=silent_fail NOTIFY=silent INTERRUPT_DND=no REOPEN=no PROMPT_TIMEOUT=300 --verbose --write \
--ignored "firefox firefox_da firefox_intl firefoxdeveloperedition firefoxesr firefoxesr_intl firefoxesrpkg firefoxpkg_intl googlechromeenterprise googlechrome microsoftedgeconsumerstable microsoftedgeenterprisestable microsoftonedrive-rollingout microsoftonedrive-rollingoutdeferred microsoftonenotereset microsoftoutlook-monthly microsoftoutlookdataremoval microsoftoutlookreset microsoftpowerpointreset zoomclient zoomgov zoomrooms microsoftteamsclassic microsoftteamsnew googledrivebackupandsync googledrivefilestream"`

It doesn't matter where I place `--options IGNORE_APP_STORE_APPS=no BLOCKING_PROCESS_ACTION=silent_fail NOTIFY=silent INTERRUPT_DND=no REOPEN=no PROMPT_TIMEOUT=300`, `--verbose- always shows:

`[NOTICE] Verbose Mode enabled.
[NOTICE] Option Count 10
[NOTICE] Installomator Options:
[NOTICE]  - IGNORE_APP_STORE_APPS="no"
[NOTICE]  - LOGGING="INFO"
[NOTICE]  - SYSTEMOWNER="0"
[NOTICE]  - NOTIFY_DIALOG="1"
[NOTICE]  - NOTIFY="success"
[NOTICE]  - INTERRUPT_DND="yes"
[NOTICE]  - LOGO="appstore"
[NOTICE]  - REOPEN="yes"
[NOTICE]  - BLOCKING_PROCESS_ACTION="tell_user"
[NOTICE]  - PROMPT_TIMEOUT="86400"`

How can I verify the `--options` I have passed are used by Patchomator?

**Comment by davidkrause-campfire** [comment]
The challenge is I just want labels generated on devices. Applications shouldn't be installed. However, in testing, I'm getting popups for application update notifications. I thought passing Installomator options would fix this issue, but unfortunately it persists.

![image (1)](https://github.com/Mac-Nerd/patchomator/assets/143036772/191c06fa-6d1f-4f6b-842a-21ad9bb287b5)
![image](https://github.com/Mac-Nerd/patchomator/assets/143036772/c10e86bb-e02d-4e96-9579-73f1c14ab3db)

**Comment by Mac-Nerd** [comment]
installomator options need to be passed all together, inside quotes, each one separated by commas. 

so
--options "setting1=yes, setting2=no"

**Comment by davidkrause-campfire** [comment]
Amazing, thank you so much! That work. I really appreciate all of your hard work on Patchomator!
