### ISSUE TITLE
Requires Fragments directory on first run

### ISSUE THREAD

**Issue by arice** [Mac-Nerd/patchomator#2]
Trying to test this out, but it seems to require the Fragments directory to be present on first run. I'm getting

```
Installomator/fragments: stat: No such file or directory
./patchomator.sh:123: bad math expression: operand expected at `) / 86400'
```

**Comment by Mac-Nerd** [comment]
First run _should_ go through and actually download and install all the requisite pieces. I'll give it a look, as the github version is out of sync with my local. Thanks.
