### ISSUE TITLE
Installed app that wasn't installed in /Applications

### ISSUE THREAD

**Issue by gustaf08** [Mac-Nerd/patchomator#22]
Testing today for the first time via Jamf Pro and overall it works pretty well. 

But when testing on my machine it found Google Chrome.app in my Autopkg folder (/Users/myuser/Library/AutoPkg/Cache/local.pkg.GoogleChrome/GoogleChrome/Applications/Google Chrome.app) and then ran installomator to install it to /Applications.

How can this be avoided? Other than stopping using autopkg. :)

**Comment by Mac-Nerd** [comment]
Looking at adding an option to only recognize apps in default locations - i.e. not in /Users

**Comment by robjschroeder** [comment]
Hey @Mac-Nerd , for App Auto-Patch we are using the following, it may help you out as well
https://github.com/robjschroeder/App-Auto-Patch/blob/fa9d1244042b11784fe68fe6fbe9e1d5d1b00d94/App-Auto-Patch-via-Dialog.zsh#L1112C9-L1121C15

**Comment by Mac-Nerd** [comment]
1.1.1 changes discovery mode to only search in default app install locations /Applications /Library and /usr/local
added `--everywhere` option to override new behavior, in case you want to search the whole system.
